<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="69" started-at="2012-08-24T13:37:09Z" finished-at="2012-08-24T13:37:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="69" started-at="2012-08-24T13:37:09Z" finished-at="2012-08-24T13:37:09Z">
      <class name="com.marvinformatics.kissthrow.ThrowsTest">
        <test-method status="PASS" signature="validateMethods()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="validateMethods" is-config="true" duration-ms="19" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateMethods -->
        <test-method status="FAIL" signature="silentThrowException()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="silentThrowException" duration-ms="16" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception java.lang.Exception but got org.testng.TestException: 
Expected exception java.lang.Exception but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception java.lang.Exception but got org.testng.TestException: 
Expected exception java.lang.Exception but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1251)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.lang.Exception but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:764)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	... 16 more
Caused by: java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at com.marvinformatics.kissthrow.ThrowsTest.silentThrowException(ThrowsTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- silentThrowException -->
        <test-method status="PASS" signature="validateMethods()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="validateMethods" is-config="true" duration-ms="0" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateMethods -->
        <test-method status="FAIL" signature="silentThrowIOException()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="silentThrowIOException" duration-ms="1" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception java.io.IOException but got org.testng.TestException: 
Expected exception java.io.IOException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception java.io.IOException but got org.testng.TestException: 
Expected exception java.io.IOException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1251)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.io.IOException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:764)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	... 16 more
Caused by: java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at com.marvinformatics.kissthrow.ThrowsTest.silentThrowIOException(ThrowsTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- silentThrowIOException -->
        <test-method status="PASS" signature="validateMethods()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="validateMethods" is-config="true" duration-ms="0" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateMethods -->
        <test-method status="FAIL" signature="silentThrowRuntimeException()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="silentThrowRuntimeException" duration-ms="1" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception java.lang.RuntimeException but got org.testng.TestException: 
Expected exception java.lang.RuntimeException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception java.lang.RuntimeException but got org.testng.TestException: 
Expected exception java.lang.RuntimeException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1251)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.lang.RuntimeException but got java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:764)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	... 16 more
Caused by: java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at com.marvinformatics.kissthrow.ThrowsTest.silentThrowRuntimeException(ThrowsTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- silentThrowRuntimeException -->
        <test-method status="PASS" signature="silentThrowThrowable()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="silentThrowThrowable" duration-ms="1" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
	Unhandled exception type Throwable
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Throwable

	at com.marvinformatics.kissthrow.ThrowsTest.silentThrowThrowable(ThrowsTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- silentThrowThrowable -->
        <test-method status="PASS" signature="validateMethods()[pri:0, instance:com.marvinformatics.kissthrow.ThrowsTest@c8a3c71]" name="validateMethods" is-config="true" duration-ms="0" started-at="2012-08-24T10:37:09Z" finished-at="2012-08-24T10:37:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateMethods -->
      </class> <!-- com.marvinformatics.kissthrow.ThrowsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
